<?php

namespace Medieval\Framework\Config;

use Medieval\Config\AppConfig;

class FrameworkConfig {

    const PHP_EXTENSION = '.php';

    const DEFAULT_AREA = AppConfig::DEFAULT_AREA;
    const AREA_SUFFIX = AppConfig::AREA_SUFFIX . DIRECTORY_SEPARATOR;
    const DEFAULT_CONTROLLER = AppConfig::DEFAULT_CONTROLLER;
    const CONTROLLER_SUFFIX = AppConfig::CONTROLLER_SUFFIX;
    const DEFAULT_ACTION = AppConfig::DEFAULT_ACTION;

    const VENDOR_NAMESPACE = AppConfig::VENDOR_NAMESPACE . DIRECTORY_SEPARATOR;
    const CONTROLLERS_NAMESPACE = AppConfig::CONTROLLERS_NAMESPACE . DIRECTORY_SEPARATOR;
    const AREAS_NAMESPACE = AppConfig::AREAS_NAMESPACE . DIRECTORY_SEPARATOR;
    const REPOSITORIES_NAMESPACE = AppConfig::REPOSITORIES_NAMESPACE . DIRECTORY_SEPARATOR;
    const VIEW_MODELS_NAMESPACE = AppConfig::VIEW_MODELS_NAMESPACE . DIRECTORY_SEPARATOR;
    const VIEWS_NAMESPACE = AppConfig::VIEWS_NAMESPACE . DIRECTORY_SEPARATOR;
}